//region auth
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";

export const REGISTRATION_REQUEST = "REGISTRATION_REQUEST";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_ERROR = "REGISTRATION_ERROR";
//endregion

//region users page
export const FETCH_ALL_USERS_REQUEST = "FETCH_ALL_USERS_REQUEST";
export const FETCH_ALL_USERS_SUCCESS = "FETCH_ALL_USERS_SUCCESS";
export const FETCH_ALL_USERS_ERROR = "FETCH_ALL_USERS_ERROR";

export const FETCH_FRIENDS_REQUEST = "FETCH_FRIENDS_REQUEST";
export const FETCH_FRIENDS_SUCCESS = "FETCH_FRIENDS_SUCCESS";
export const FETCH_FRIENDS_ERROR = "FETCH_FRIENDS_ERROR";

export const FETCH_SUBSCRIBERS_REQUEST = "FETCH_SUBSCRIBERS_REQUEST";
export const FETCH_SUBSCRIBERS_SUCCESS = "FETCH_SUBSCRIBERS_SUCCESS";
export const FETCH_SUBSCRIBERS_ERROR = "FETCH_SUBSCRIBERS_ERROR";

export const FETCH_SUBSCRIPTIONS_REQUEST = "FETCH_SUBSCRIPTIONS_REQUEST";
export const FETCH_SUBSCRIPTIONS_SUCCESS = "FETCH_SUBSCRIPTIONS_SUCCESS";
export const FETCH_SUBSCRIPTIONS_ERROR = "FETCH_SUBSCRIPTIONS_ERROR";
//endregion

//region profile page
export const FETCH_PROFILE_REQUEST = "FETCH_PROFILE_REQUEST";
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
export const FETCH_PROFILE_ERROR = "FETCH_PROFILE_ERROR";

export const SUBSCRIBE_TO_USER_REQUEST = "SUBSCRIBE_TO_USER_REQUEST";
export const SUBSCRIBE_TO_USER_SUCCESS = "SUBSCRIBE_TO_USER_SUCCESS";
export const SUBSCRIBE_TO_USER_ERROR = "SUBSCRIBE_TO_USER_ERROR";

export const UNSUBSCRIBE_FROM_USER_REQUEST = "UNSUBSCRIBE_FROM_USER_REQUEST";
export const UNSUBSCRIBE_FROM_USER_SUCCESS = "UNSUBSCRIBE_FROM_USER_SUCCESS";
export const UNSUBSCRIBE_FROM_USER_ERROR = "UNSUBSCRIBE_FROM_USER_ERROR";
//endregion

//region posts
export const FETCH_USER_POSTS_REQUEST = "FETCH_USER_POSTS_REQUEST";
export const FETCH_USER_POSTS_SUCCESS = "FETCH_USER_POSTS_SUCCESS";
export const FETCH_USER_POSTS_ERROR = "FETCH_USER_POSTS_ERROR";

export const CREATE_USER_POST_REQUEST = "CREATE_USER_POST_REQUEST";
export const CREATE_USER_POST_SUCCESS = "CREATE_USER_POST_SUCCESS";
export const CREATE_USER_POST_ERROR = "CREATE_USER_POST_ERROR";
//endregion

//region chats
export const FETCH_USER_CHATS_REQUEST = "FETCH_USER_CHATS_REQUEST";
export const FETCH_USER_CHATS_SUCCESS = "FETCH_USER_CHATS_SUCCESS";
export const FETCH_USER_CHATS_ERROR = "FETCH_USER_CHATS_ERROR";

export const FETCH_CHAT_EXISTS_REQUEST = "FETCH_CHAT_EXISTS_REQUEST";
export const FETCH_CHAT_EXISTS_SUCCESS = "FETCH_CHAT_EXISTS_SUCCESS";
export const FETCH_CHAT_EXISTS_ERROR = "FETCH_CHAT_EXISTS_ERROR";

export const FETCH_CHAT_REQUEST = "FETCH_CHAT_REQUEST";
export const FETCH_CHAT_SUCCESS = "FETCH_CHAT_SUCCESS";
export const FETCH_CHAT_ERROR = "FETCH_CHAT_ERROR";
//endregion

//region news
export const FETCH_USER_NEWS_REQUEST = "FETCH_USER_NEWS_REQUEST";
export const FETCH_USER_NEWS_SUCCESS = "FETCH_USER_NEWS_SUCCESS";
export const FETCH_USER_NEWS_ERROR = "FETCH_USER_NEWS_ERROR";
//endregion
